### ISSUE TITLE
Seem to have issue loading in data.

### ISSUE THREAD

**Issue by knuthfa** [dmcglinn/quant_methods#1]
Loaded data with
> dat <- read.csv(file = "./tgpp.csv", header=T)

Listed columns and rows with
> ncol(dat)
[1] 1
> nrow(dat)
[1] 57729

or simply
> dim(dat)
[1] 57729     1

On github I can see that there are inf act 11 columns, not just 1, so I must be doing something wrong. Anyone have an idea?

**Comment by dmcglinn** [comment]
Double check that the file downloaded properly. Did you make sure to
download the raw file? Simplest thing to do is find the file and open it in
excel.

Dan

**Comment by knuthfa** [comment]
Got it. Download was faulty.

**Comment by dmcglinn** [comment]
Hey folks,

I wanted to give you the heads up that I updated assignment 2 by
adding some more a few more hints and extra context to questions 3 and
5.

Also if you have a github account then I strongly recommend you to
"watch" the course repository so that you are notified when someone in
the class submits and issue. At the top of the webage you'll just need
to click on the eye button.  There are two active issues right now -
thanks for those Friedrich! Feel free to reply, expand, or create your
own issues as you work through the assignment. Ideally we'll all be
able to help contribute to each other's success in this collaborative
online environment (yea I know open science blah blah blah ;)

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey folks,

Just a quick update. David Leslie brought up a good point that in this
week's HW I requested to know which variable is most strongly
"correlated" with tree cover. He was tempted to leave regression
modeling and use a correlation analyses. I just wanted to remind
everyone that there is a strong relationship between correlation and
regression. I through together this mini-lesson:

https://github.com/dmcglinn/quant_methods/blob/master/lessons/standardized_beta_coefficents.Rmd


If you'd like to work your way through it you can learn about
standardized regression coefficients and their relationship with the
classic correlation coefficients you probably know quite well.

Let me know if you have questions.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey folks,

I just wanted to let you guys know that the course webpage is finally up
and running although still likely a bit buggy. Please let me know if you
find bugs or have suggestions for content or page design.

http://dmcglinn.github.io/quant_methods/

Thanks!

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey Folks,

There will be no required HW this week. If you would like extra practice
with loops as discussed in class I have created an extra credit exercise.
This is totally optional if you chose to complete it I will give you
feedback and give you extra credit points.

http://dmcglinn.github.io/quant_methods/assignments/loop_excercises

I will be hold office hours tomorrow from 8:30 to 9:30 AM in HWWE 203.

Thanks!

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey folks,

Just in case I was not clear there is no official HW due this week. If
you would like to complete the optional loop assignment go for it.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey folks,

Thanks for a great class tonight. I just wanted to let you know that I
have significantly updated question 2 and dropped question 3 from the
HW assignment.

http://dmcglinn.github.io/quant_methods/assignments/spatial_models/

This should not change again. Please let me know if you have questions.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey Folks,

I need to cancel office hours this Friday. If you have questions about
the HW please either email me directly or schedule and individual
meeting with me.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey Folks,

I'm going to try to squeeze folks in for 30 minute meetings this
Tuesday. If Tuesday does not work for you then there may be time
Wednesday morning and right before class.

Here is a doodle poll to sign up for a Tuesday meeting time. Just
click a single time slot that you want. This will be a first come
first serve basis unless there is a good reason to reschedule someone.

http://doodle.com/v8eiarxy75y4x57v

Clay I know that is a busy day for you. Trevor I think you might only
be available at 1 pm.  Matt I know that Wednesday before class likely
works best for you. Email me if Tuesday does not work and you need to
setup a meeting on Wednesday.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey Folks,

This week in class you'll be delivering your project pitches and the
group will be providing constructive criticism. Please let me know if
you'd like to meet one more time before class on Tuesday (9-3pm) or
Wednesday (9-1 pm) to try to iron out any questions or thoughts you
have. Of course email is always great too!

Hope you all had a great break!

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey folks,

This is our last big week of working on code for projects. If you're not
posting code to your github project page consider this your last warning. I
have no way of checking up on your progress if you are not doing this.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Folks,

If you want to catchup with me I'll have office hours from 11:30 to 12:30.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Hey Folks,

Just as a heads up last week in class ya'll decided we would do
another round of peer-code review this week of class. So make sure all
your most recent updates are pushed to github in time for class.

Dan

-- 
Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by dmcglinn** [comment]
Though you guys would like these. Katie see the data vis one we know that you love your graphs! 



http://www.rstudio.com/resources/cheatsheets/


Dan



​

**Comment by davidmhood** [comment]
Cool
