### ISSUE TITLE
Unexpected '}' in my if statement

### ISSUE THREAD

**Issue by Jordylacrosse** [dmcglinn/quant_methods#12]
Hello all, 

I am trying to create an 'if' statement in my R code and am stuck on one of the frustrating outcomes of a missing/extra component in my R code. I've been tinkering with it for over an hour, and need some help.   No matter which way I put it, the error message I get is: Error: unexpected '}' in "  }".  Here is my code:

``` r
vectorx<-c(1:10)
vectorx

 y<-0
for(i in 1:10)
  {
  y[i]<-vectorx[i]+vectorx[i+1]
  {
  if(is.na(y[i] > 10))
    }
  }

print(y)
```

The "is.na" code is designated to set any value to NA if greater than 10. (I had a different R code originally, but was prompted to provde a TRUE/FALSE statement.) The way around that way using the is.na function.

**Comment by dmcglinn** [comment]
hey @Jordylacrosse thanks for your question. quick note can you edit your R code in your question so that it is properly formatted for markdown (i.e., exactly how you would do this in an Rmarkdown doc). My first thought is that it is difficult to spot the problematic `}` because you have not spaced over 4 times for each level of the loop. Here is how your code should look:

``` r
y <- 0
for(i in 1:10) {
    y[i] <- vectorx[i] + vectorx[i + 1]
    # { 
    # you do not need the commented { in the line above 
    if (is.na(y[i] > 10)) {
        # do some stuff
    }
}

y
```

**Comment by TomNash** [comment]
The function `is.na()` doesn't set any value to `NA` but rather check if the inputs are `NA`. Example, `is.na(NA)` returns `TRUE`, `is.na("hello")` returns `FALSE`. You can read more about the function and see some examples if you do `?is.na`.

**Comment by Jordylacrosse** [comment]
Thanks guys for the help!
Jordy

**Comment by dmcglinn** [comment]
thanks @TomNash! @Jordylacrosse when you get a chance please add the R markdown tags to the code in your question - as I noted above this is identical to how to define a block of R code in an Rmarkdown doc.

**Comment by mikala-randich** [comment]
``` r
y=0
x=1:10
for(i in 1:10) {
  y[i] = x[i] + sum(x[1:i]) + 1
  if (y[i]<=10) {
    print(y)
  }
  else if (y[i]>10) {
    print ('NA')
  }
}
y
```

Hi everyone, this is what I have so far. The problem I'm having is that the y[i] output starts at 3 instead of 1, so I think there's a problem with my y[i] expression. Any ideas?

**Comment by dmcglinn** [comment]
hey @mikala-randich I think we need a new issue for your question because it is not directly related to the `}` issue that @Jordylacrosse was having. Please start a new thread. Thanks!
