### ISSUE TITLE
car package

### ISSUE THREAD

**Issue by andersenme** [dmcglinn/quant_methods#15]
I installed the car package and it shows up in my packages in RStudio but when I try to use it I get this error message:
`> library(car)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘nloptr’
Error: package or namespace load failed for ‘car’`

Obviously I can't use the anova function or anything else until I get this worked out. As far as I can tell it installed in the right directory. Any suggestions?

**Comment by TomNash** [comment]
Try this:

```
install.packages("car", repos=c("http://rstudio.org/_packages", "http://cran.rstudio.com"))
library(car)
```

If that doesn't work, then just install `nloptr` with `install.packages("nloptr")`

**Comment by andersenme** [comment]
I fixed this by installing the package nloptr, everything seems to be working fine.

**Comment by dmcglinn** [comment]
Great! Thanks for reporting the error and thanks @tomnash for the fix. Can you please close the issue now.

Dan
