### ISSUE TITLE
Trouble with pseudo_r2

### ISSUE THREAD

**Issue by shoresk** [dmcglinn/quant_methods#16]
Is anyone else having trouble with generating an r-squared value for the glm models? I copied and pasted the function from the assignment, simply changing "glm_mod" to "glm_gen" which is one of my models: 

``` r
pseudo_r2 = function(glm_gen) {
    1 - glm_gen$deviance / glm_gen$null.deviance
}
```

but it isn't giving me a value...

**Comment by smccau** [comment]
Sarah Kate,

You're making a function that will fit for any GLM that you have.  You should be able to just keep the code as it was from the website, and it should be gucci.  You then can use it as, for example:

``` r
pseudo_r2 = function(glm_mod) {
    1 - glm_mod$deviance / glm_mod$null.deviance
}

pseudo_r2(glm_gen)
```

And it should return something valuable.  You can use it also on your other GLM for A. fraseri.

**Comment by dmcglinn** [comment]
Yep I agree with @samuelmccauley!

**Comment by shoresk** [comment]
Yeah, I got it, thanks!
