### ISSUE TITLE
No output for glm function

### ISSUE THREAD

**Issue by sarahwie** [dmcglinn/quant_methods#17]
I am getting the following error when I run glm:

`
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
`

My code is the following:
`
acer = trees[trees$species == 'Acer rubrum', ]
`
`
acer_glm = glm(cover ~ . , data= acer, family='poisson')
`

Any idea why this is happening? I followed the code given in the assignment exactly so I'm not sure.

**Comment by dmcglinn** [comment]
When you use the shorthand `resp ~ .` all the columns in dataframe except `resp` will be included as explanatory variables. The error is telling you one of your explanatory variables is a factor with only one level. I'm guessing it is the field `Species` which in your case will all be __Acer rubrum__

What do you think is the solution in this case?

**Comment by sarahwie** [comment]
Got it! I had to remove both the "spcode" and the "species" column and got rid of "plotID" as well while I was at it since that's not really useful.

For the record in case anyone else has this issue, here's what I did:
`
acer = trees[trees$species == 'Acer rubrum', -c(1,2,3)]
`
`
acer_glm = glm(cover ~ ., data= acer, family='poisson')
`
