### ISSUE TITLE
Homework Discussion

### ISSUE THREAD

**Issue by Jordylacrosse** [dmcglinn/quant_methods#18]
Hi friends,

Just trying to initiate some discussion here on our dune homework and to alleviate some confusion on interpreting some of the results. 

``` r
cca_dune<-cca(dune ~ dune.env$A1 + dune.env$Moisture + dune.env$Management + dune.env$Use +
               dune.env$Manure)

cca_dune
plot(cca_dune, ylim=c(-20, 20), display=c('sp','bp'), scaling=1)
#this lets me view a cca plot of the variables of dune.env

plotdune<-plot(cca_dune, ylim=c(-20, 20), display=c('sp','bp'), scaling=1)
plotdune
#this lets me view the first two cca axes for each species and for each variable

anova(cca_dune, by='margin', permutations = 10)

```

First off, regarding the CCA plot - does this look messy to anyone else? I'm not satisfied with it. 
I see the different levels of variables (example: Use.L, Use. Q, etc) pointing in different directions, which indicates there is an effect due to the different types of the variable Use. (correct me if I am interpreting that wrong). This goes for management types as well, since each vector is pointing in a different direction (so there is a strong effect of management on dune cover). 
But this seems to be messy viewing (and I feel I am spinning my wheels on what may have more of an effect over another variable), and I would like to view a CCA plot of the variables overall (rather than looking at the specific levels for each variable). So my question is: does anyone concur with me ? and if so, HOW do you get about viewing the CCA plot with overall predictor variables?

Secondly, I ran the plot of dune and it appears to spit out the CCA values associated with each variable and the levels of each variable (this is my 4th line of code)... I am having a hard time reading these values for the predictor variables...is it like reading the cca output for total variance, variance explained, and variance unexplained? 
So are the individual CCA values associated with each variable and level the amount of variance explained for that specific variable/level?

I tried to make those questions/descriptions as clear as possible. 
Thank you for the discussion/feedback/help.

Cheers,

Jordy

**Comment by dmcglinn** [comment]
Thanks @Jordylacrosse for bringing these issues up here and in class. One quick thing I wanted to note is that I added a function `r2_adj_cca` to the script  `./scripts/utility_functions.R` for computing R^2 and R^2 adjusted for RDA and CCA. When using CCA you need to provide the number of permutations - at least 100 but more is good (this is slow though).
