### ISSUE TITLE
Q2: Unable to add richness column to trees

### ISSUE THREAD

**Issue by knuthfa** [dmcglinn/quant_methods#2]
I was able to create and summarize a new variable called richness with the following lines:

trees = read.csv('./treedata.csv')
richness = with(trees, tapply(species, plotID, FUN = function(x) length(unique(x))))
summary(richness)

This returns a bunch of nice information about this newly created variable and pretty much answers Q2. Nice. The problem later in Q5 is that I am unable to model richness as my response (y), given that it is not stored as a column in my initial database trees. richness is separate from trees. So I tried the following, to create richness as a new column in trees:

trees$richness = with(trees, tapply(species, plotID, FUN = function(x) length(unique(x))))

This won't seem to work because it is trying to add richness values for only 935 rows (unique plots) to the total 8971 rows in the data. 

I also tried to merge trees and richness using the following line:

merge(trees, richness, by=plotID, all=TRUE)

But that won't work, since richness doesn't actually have a column called plotID. It seems to have two columns, one called row.names and one called x. Should I rename the columns and then merge? Haven't figured out how to do that yet and I am getting the feeling I am going down a rabbit hole here...

**Comment by dmcglinn** [comment]
Great job coming up with an efficient method to compute richness!

As I noted in #3 one simple solution that you are on the cusp of getting is a successful merging of the `richness` vector with the larger `trees` data.frame. See my description and hints in #3 and let me know if you have more questions.

**Comment by knuthfa** [comment]
Good to go here. Closing. Thx!
