### ISSUE TITLE
Shortcut to creating full model without having to rename variables

### ISSUE THREAD

**Issue by TomNash** [dmcglinn/quant_methods#20]
Hopefully this will make the second part go a little more smoothly for the full model:

So we have the vector of species to use as predictors and the species of interest:

```
sp_ids = c("Cordia.lasiocalyx", "Hirtella.triandra",
           "Picramnia.latifolia", "Quassia.amara",
           "Tabernaemontana.arborea", "Trattinnickia.aspera", 
           "Xylopia.macrantha")
sr_response <- BCI$Drypetes.standleyi
```

We can create a data frame of the species of interest, followed by the predictor species, then the X/Y coordinates for each plot

```
# analgous to: sr_dat = data.frame(sr, mite.env, mite.xy) from the lesson
sr_full_dat <- data.frame(sr_response,BCI[,which(colnames(BCI) %in% sp_ids)],BCI_xy)
```

The formula is usually written as `reponse ~ term_1 + term_2 + ... term_n` so we'd have to write out each species name or rename them to something short, but we can use `paste` to combine them all with plus signs in-between. We can't use the `data= ...` term this way, so we call the `gls` using the command `with()` using the syntax `with(data.frame,gls(formula)` so it knows where these terms are coming from:

```
full_fmla <- as.formula(paste("sr_response ~ ", paste(sp_ids, collapse= "+")))
sr_full_lm <- with(sr_full_dat,gls(full_fmla))
```

**Comment by dmcglinn** [comment]
Thanks @TomNash! Very nice suggestions. We can make it even easier if we use the "." shortcut for model specification as such: 

``` r
sp_ids = c("Drypetes.standleyi", "Cordia.lasiocalyx", "Hirtella.triandra",
           "Picramnia.latifolia", "Quassia.amara",
           "Tabernaemontana.arborea", "Trattinnickia.aspera", 
           "Xylopia.macrantha")
bci_sp = subset(BCI, select=sp_ids)

full_gls = gls(Drypetes.standleyi ~ ., data=bci_sp)
```

There is no real need to merge `BCI_xy` into the `data.frame` of species data. Also just as a note in the the less I named the object `sr` as shorthand for species richness which is the number of species that occur in a sample. In the context of the current HW `sr` would be a confusing object name prefix.

**Comment by dmcglinn** [comment]
Actually my comment above although will work for the simple gls model will break when trying to specify the correlation structure see #22
