### ISSUE TITLE
Not able to make community matrix off of data subset

### ISSUE THREAD

**Issue by sarahwie** [dmcglinn/quant_methods#21]
I'm trying to make the community matrix for my BCI subset and I get an error that I need more than one column of data in my input matrix:

``` r
sub_common = BCI$Faramea.occidentalis
comm_dist = vegdist(sub_common)
```

Should I be able to do this?

**Comment by TomNash** [comment]
Simply, no, you shouldn't. `vegdist` uses [Bray-Curtis dissimilarity](https://en.wikipedia.org/wiki/Bray%E2%80%93Curtis_dissimilarity) which requires more than one species. That's all I can say without any more background knowledge. My understanding is you'd use `vegdist` for multivariate models, but in this case you're doing a univariate analysis. I think `dist(sub_common)` and `dist(BCI_xy)` should be sufficient.

**Comment by dmcglinn** [comment]
Thanks @TomNash! I agree.

**Comment by sarahwie** [comment]
Okay, thanks!
