### ISSUE TITLE
Error in terms.formula(el) : '.' in formula and no 'data' argument

### ISSUE THREAD

**Issue by smccau** [dmcglinn/quant_methods#22]
This for me literally feels like being [Brazil](https://en.wikipedia.org/wiki/Brazil_v_Germany_%282014_FIFA_World_Cup%29).  

I'm chugging along and I encounter the error mentioned in the title:

``` r
> anova(full_gls, full_rat_nug)
Error in terms.formula(el) : '.' in formula and no 'data' argument
```

And here is the code I'm working with (more or less):

``` r
sp_ids = c("Drypetes.standleyi", "Cordia.lasiocalyx", "Hirtella.triandra",
           "Picramnia.latifolia", "Quassia.amara",
           "Tabernaemontana.arborea", "Trattinnickia.aspera", 
           "Xylopia.macrantha")
# Declare species IDs used for this question.

abun_dat = data.frame(BCI, BCI_xy)
# Create data frame for BCI and BCI_xy data

BCI_sp = subset(abun_dat, select=sp_ids)
# Create subset of abun_dat that holds only the data from sp_ids

full_gls = gls(Drypetes.standleyi ~ ., data = BCI_sp)
# Create GLS for Model 2 comparing abundances of D. standleyi vs. numerous 
# select species

full_rat_nug = update(full_gls, corr=corRatio(form=~'x' + 'y', nugget=T))
# Create and plot full_gls updated to the rational quadratic error model
# with a nugget.

anova(full_gls, full_rat_nug)
# Compare the original model and one with a rational quadratic error structure
# and nugget.
```

I receive the error once I reach the `anova` for the two full GLS models.  I tried poking around on the internet, but everything I found had something to do I believe with the `.` in something like my `Drypetes.standleyi ~ .`.  

So, uhh, what?

Thank you!

Sam

**Comment by dmcglinn** [comment]
I'm not sure if this is causing your error but 'x' and 'y' are meaningless in the correlation structure component of the model. Any idea what those should be so they refer to the sample coordinates?

**Comment by andersenme** [comment]
I had the same error after I had defined all my gls models and tried to do the anova on them. I was able to fix it by going back and writing out the entire formula instead of using the`Drypetes.standleyi ~ .` shortcut in the model definitions.  Apparently having the `.` shortcut messes up the anova, not sure why.

**Comment by dmcglinn** [comment]
Ok so I looked into this and it seems that @TomNash's suggestion of including the x and y variables in the data.fame used as the model data argument is necessary. I thought one would be able to supply this from a different data.frame but this seems to be causing problems. So it appears that to solve these problems you need to 
1. construct a data.frame that contains both the response and explanatory variables you wish to use and also includes the spatial coordinates.
2. build your initial model and explicitly identify the explanatory variables to include in the model (i.e., don't use the "." shortcut of model specification). 

This should then result in no errors. This comment applies to #20 and #23

**Comment by smccau** [comment]
**Solved for my own code:**

I took @andersenme's advice both here and in [#23](https://github.com/dmcglinn/quant_methods/issues/23).

 After naming all of the species I wanted the model to run while using @dmcglinn's alternative and @andersenme's work-around, I got the `anova` to run without an error.  

I should also note that I had similar trouble in having `x` and `y` not found as objects in my code/environment (as in [#23](https://github.com/dmcglinn/quant_methods/issues/23)), so I quoted them out understanding that's what I probably should have done to get the values from `BCI_xy`.  After using @andersenme's advice in declaring `x = BCI_xy$x` and `y = BCI_xy$y`, I got different and (obviously) more significant results in both of my `anova`.

Thank you @dmcglinn and @andersenme!
