### ISSUE TITLE
Git/Pushing Problem

### ISSUE THREAD

**Issue by mikala-randich** [dmcglinn/quant_methods#24]
Hi everyone,

I'm having issues pushing my assignment to my repo (as always), any advice on how to get my file to show up in the upper right-hand "Git" window so I can commit and push it? 

Thanks,

Mikala

**Comment by ghost** [comment]
Hey @mikala-randich !

This worked for me:
-Go to the Git tab in R-Studio (the one on the top right)
-Click the document you want to push. Press "Commit". 
-The R-Studio pop-up will appear. Type your 'changes' on the right side, and press commit. 
-Go back to the Git tab in R-Studio. Press the "Push" button. (The document you want to push will not be here. It wont be visible, but thats okay). 
-The document should be loaded in your repository on github.com

**Comment by mikala-randich** [comment]
Thanks @kristinlinesch! The main issue is that the files I want to commit (both the .Rmd and the .pdf files for the homework) aren't showing up in that Git tab in R-studio. I can't figure out how to make them appear.

**Comment by ghost** [comment]
@mikala-randich -

Your files (Rmd or pdf) must be saved under the project linked to your github repository. I was having trouble with this a few weeks ago, but @dmcglinn had to fix this for me. If this is the issue, I am sorry to say, I cannot help. Sorry
