### ISSUE TITLE
Sorting vector based on a vector of indices

### ISSUE THREAD

**Issue by sarahwie** [dmcglinn/quant_methods#27]
I'm have a vector of indices, `row_indices`, that represent the positions in one vector, `refugeesum`, where the values of another vector (`mapChoices`) are found. I want to order the names and values of `refugeesum` to match the order of the names of mapChoices.The sort and order functions I've found would just order by increasing or decreasing value, not off the value of another vector. Any ideas on how to do this?

`
row_indices = match(mapChoices, names(refugeesum))
`

**Comment by dmcglinn** [comment]
it's way easier then you think `mapChoices[row_indices]`
