### ISSUE TITLE
Rmd to PDF

### ISSUE THREAD

**Issue by conradcd** [dmcglinn/quant_methods#30]
So I knit to PDF and it spit out a wonderfully formatted 35 page pdf document but when I saved it with the .pdf extension , I got a warning not to change that (the extension that is) yet I was currently looking at it in adobe acrobat and this file now won't open. So I reknit to PDF and saved again, this time without changing the extension, now I have a .Rmd file that automatically opens in Rstudio

**Comment by kristinlinesch** [comment]
Hi Dan,

I took your class a few years ago, but I am still getting these messages
for some reason. Can you take me off the list?

Thanks!
Kristin
