### ISSUE TITLE
Importing ".tiff" files into R

### ISSUE THREAD

**Issue by prouxzs** [dmcglinn/quant_methods#32]
I'm trying to import four rasters from one geographic area into R: depth, aspect, slope, and backscatter intensity.  My intention is to define a geographic box on the rasters and extract georeferenced data from all four into a table that I can use for modeling presence-absence of black corals.  I haven't been able to import the files. Any help would be greatly appreciated!! Here's what I've tried:

```{r}
library(raster)
raster('./Data/Rasters/File_Name.tiff')
```
^This was the error I got:
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer", : Cannot create a RasterLayer object from this file. (file does not exist)

```{r}
library(rgdal)
readGDAL('./Data/Rasters/File_Name.tiff')
```
^This was the error I got:
Error in .local(.Object, ...) : `NF-08-15-OE_CUBE_10m_slope.tiff' does not exist in the file system, and is not recognised as a supported dataset name.

```{r}
library(rtiff)
```
^ I couldn't even install this package - I think it might cost money.

**Comment by TomNash** [comment]
First thing I'd check is your path. You're using the local path to the file, make sure you're in the directory you think you are in with `getcwd()` and then `setwd()` to change to the appropriate directory if you need to move.

When in doubt, you can always use full path but you lose portability that way.
