### ISSUE TITLE
change values in one data frame using another data frame as reference 

### ISSUE THREAD

**Issue by conradcd** [dmcglinn/quant_methods#33]
Hey guys, 
a large portion of my bird data has the bird species as a four letter abbreviation (Green Heron = GRHE) in its own column. I've got another data frame with all 140 abbreviations and their full names. How do I use this as a lookup table to fill in the new column with the full name? I know I could use a for loop but individually typing all 140 would be a nightmare. 
This function "addNewData" 
https://gist.github.com/dfalster/5589956#file-addnewdata-r 
seems like it would work but install.packages("addNewData") won't work on my version of r 

thanks

**Comment by katiebalcewicz** [comment]
You can use the match function.
`indices = match(df$abbr, lookuptable$abbr)`
`df$fullname = lookuptable$fullname[indices]`

**Comment by TomNash** [comment]
The gist you referenced isn't a package but rather a function. You can bring it into your environment by doing one of the following:

1. Download the [R script](https://gist.githubusercontent.com/dfalster/5589956/raw/5f9cb9cba709442a372c2e7621679a5dd9de1e28/addNewData.R) and running `source(addNewData.R)`

2. Source the gist directly using these two commands
```
library(devtools)
source_gist("https://gist.github.com/dfalster/5589956")
```

**Comment by MRittinghouse** [comment]
One question - is there any particular need to use this function as opposed to just, say merging in the appropriate look up value? 

You could probably solve this by using one merge command to bring in the full names and use the four letter abbreviation as your merge key. See the documentation here at: http://stat.ethz.ch/R-manual/R-devel/library/base/html/merge.html

**Comment by dmcglinn** [comment]
thanks @MRittinghouse @katiebalcewicz and @TomNash for your great and helpful comments @conradcd did this solve your problem. If so can you please close the issue otherwise let us know where you're still having problems.

**Comment by conradcd** [comment]
thanks guys!
