### ISSUE TITLE
Confused about output for assignment 2 sum of a sequence

### ISSUE THREAD

**Issue by enriqueza** [dmcglinn/quant_methods#36]

**Comment by enriqueza** [comment]
Hey all, I was confused about why we are supposed to be getting the first element of y as 1. I've tried to make some code that will give me the output starting with the numbers 1,3,6, but it is not working.
Here is what I have so far:

```
x = c(1:10)
y= NULL
for (i in x) {
  y[i]= x+x[i]
}
y
```

Anyone have any hints or advice? Please let me know. Thanks.

**Comment by jensenac** [comment]
I am still trying to find the right one too.  When I figure out a code that works I will let you know!

**Comment by czwartackisr** [comment]
I had the same code/formula as you.  Then Dan walked me through the right way in class.  Instead of:
`y[i] = x+x[i]` try `y[i] = sum(x[1:i])`

This sums the `x` starting at 1 running through the index of `x` at point of `y`.

**Comment by dmcglinn** [comment]
Thanks @enriqueza for this great question! Bonus points for being the first to post! Let's break down your original attempt to see what that was not working properly. 

So we have the vector `x` and we would like to generate the vector `y` where each element of the `y` vector is a sum of `x` up to that index of `y`. The reason that ` y[i]= x+x[i]` does not work is that you have `x + x[i]` which essentially says sum to each element of `x` the ith value of `x`. This generates a vector of the same length as `x` when what we actually want to generate is just a single value just the ith value of `y`. Nice job recognizing that `y` should be indexed by `i` as `y[i]`. 

@czwartackisr was correct I suggested that `x + x[i]` should be replaced with `sum(x[1:i])` does anyone want to attempt to explain why this provides the correct solution in this case. There are other ways this could be coded as well that will give the correct answer too.
