### ISSUE TITLE
How to post an issue

### ISSUE THREAD

**Issue by dmcglinn** [dmcglinn/quant_methods#37]
If this is your first time using github issues I just want to point out that like Rmarkdown files these text windows are formatted using markdown. You can click the "Preview" button at the top of the text box to see how your issue will be formatted. If you want to share some code inline wrap the code in a single grave accent. If you want to share a whole chunk of code then wrap it with three grave accents. You can even note that the code is meant to be interpreted as R code by using ```r

**Comment by ghost** [comment]
Can I please be taken off of these emails?

Paige Pilkinton

**Comment by dmcglinn** [comment]
@paigepilk I can't do that for you. You have to unwatch the repo https://help.github.com/articles/watching-and-unwatching-repositories/
