### ISSUE TITLE
Can't Display Changes in git

### ISSUE THREAD

**Issue by jensenac** [dmcglinn/quant_methods#38]
Hi Guys,

  I successfully created my bio repository and modified my text file, but when I try to display the tracked changes nothing shows up.

In the terminal I've typed:
  
  git diff and also git diff bio.txt

This just returns me to the next command line in the terminal.

Any suggestions?  Thanks!

**Comment by lazzarom** [comment]
Try typing:
git log

**Comment by jensenac** [comment]
Thank you for the suggestion.  It did not work though.  Just sends me to the next command line.

**Comment by TomNash** [comment]
Did you add the file(s) to staging using `git add`?

**Comment by jensenac** [comment]
I did.  Everything was successful up until the display portion.

**Comment by TomNash** [comment]
`git status` should display the changes. That or `git diff --cached`.

[This should give a decent explanation of how git works with file tracking.](https://stackoverflow.com/a/8547159/3220769)

**Comment by jensenac** [comment]
Thanks for the link, Tom!

**Comment by dmcglinn** [comment]
I agree that the output of `git status` would be helpful - please post that.

**Comment by jensenac** [comment]
Issue resolved.  I ran git diff after I had already committed my changes, so it had nothing to display.  Thank you all for your help.

**Comment by Mckenziematt** [comment]
I believe I successfully created my homework repo but for some reason when I type the URL into a search engine, it doesn't load. Does anyone know what this means, or if I did something wrong.
Maybe its just my browser, I'm not sure. 
http://uniola.biology.cofc.edu:8787/?view=review_changes

**Comment by dmcglinn** [comment]
Your github repo will have an address like https://github.com/dmcglinn/planets

Where dmcglinn is your github user name and planets is the name of your repo. Uniola is the server where you are working on your files.
