### ISSUE TITLE
Issues with remotes in github

### ISSUE THREAD

**Issue by czwartackisr** [dmcglinn/quant_methods#39]
I'm having an issue connecting to github remotely.  I've created a repository in my github account, but when I try...
$ git push origin master <myfilename>
I get the message "error: cannot run rpostback-askpass: No such file or directory.

Then it asks for my username and password for my github account, but it will not let me type this info in.

Any ideas?

**Comment by dmcglinn** [comment]
Hmm, I'm not completely sure but just as a note when you type your username into the terminal it will show up but when you type your password it will appear as though you are not typing but it is recording your key strokes. You could try using Rstudio's GUI push and pull system in theory when you hit push it will pop up a little window you can type your username and password into.

**Comment by czwartackisr** [comment]
Hiidden passwords - so smart!
Thanks!
