### ISSUE TITLE
Can't read in Install.packages("ggplot2") 

### ISSUE THREAD

**Issue by jensenac** [dmcglinn/quant_methods#40]
Anyone else having difficulty reading in:  install.packages("ggplot2")  for Tuesday's lesson?

The other install packages worked fine, but ggplot2 spits out the following warning.

Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpE7uLtP/downloaded_packages’

I'm not really sure what to do with this.  Any insight would be greatly appreciated.

Thanks!

**Comment by TomNash** [comment]
Try install.packages(“ggplot2”, dependencies=TRUE)

**Comment by dmcglinn** [comment]
@TomNash 's suggestions is a good one. Also the entire text output of the error will be helpful if you still have trouble

**Comment by jensenac** [comment]
Thank you Tom and Dr. McGlinn.  Tom, your modification fixed the issue.  For anyone else that has difficulties with this package please note that the above modification worked but took more than 10 minutes to finish installing.

Cheers
