### ISSUE TITLE
Issues with Interaction Effect Model for Abies fraseri... Leverage points

### ISSUE THREAD

**Issue by jensenac** [dmcglinn/quant_methods#43]
Hey guys,

  I'm having an issue with a few of my models for Abies fraseri.  Specifically with my interaction model.

abi_int_mod<- lm(cover~elev*tci*streamdist*disturb*beers, data=ABI)
abi_int_mod
plot(abi_int_mod)

When I run the code, I get the message "not plotting observations with leverage one" and a bunch of NAs are listed.  I know this code worked for Acer rubrum, so I'm wondering if the errors I am getting are from particular data points in the sample?  This error is affecting my Anova analysis too.

Anyone else with this issue, or a suggestion?

I will try to post screen shots of my issue below.

![screen shot 2019-02-04 at 8 50 14 pm](https://user-images.githubusercontent.com/46498497/52248927-a6de6200-28be-11e9-9a59-289215da2116.png)

![screen shot 2019-02-04 at 8 49 17 pm](https://user-images.githubusercontent.com/46498497/52248932-afcf3380-28be-11e9-9ebd-39ab7571edb0.png)

**Comment by jensenac** [comment]
I'm guessing the error might have something to do with the disturb values?  Any insight would be totally rad.  Thanks, guys!

![screen shot 2019-02-04 at 9 00 54 pm](https://user-images.githubusercontent.com/46498497/52249247-0be68780-28c0-11e9-81fe-500704d67aec.png)

**Comment by dmcglinn** [comment]
This code works for me without errors: 
```r
trees <- read.csv('./data/treedata.csv')
ABI <- subset(trees, species = "Abies fraseri")
abi_int_mod <- lm(cover ~ elev * tci * streamdist * disturb * beers, data=ABI)
summary(abi_int_mod)
```
Which makes me think something happened to your object ABI that is causing a bug. Can you run my code snippet and see if it works. 

Also this brings up the question of whether or not the all interaction model is a useful model to consider. Let's say hypothetically it was found to be the best model using AIC - how would you explain this model to stake holders that need to manage the forest? Remember a model is only as useful as we can use it. So at the outset we need to think carefully about how we plan to use the model (exploratory / testing / prediction / some combination). 

Also this is minor but these issues are github flavored markdown so if you wrap your code chunks with the 3 grave accents then it will be properly formatted.
