### ISSUE TITLE
#2 on the spatial modeling homework

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#45]
Hey I'm a little confused on what to do for #2 on the spatial modeling homework. 
For explaining Drypetes standleyi abundance, I set up the 1-variable model like this:

`standleyi_1var_lm = gls(Drypetes.standleyi ~ Cordia.lasiocalyx, data = BCI)`

Where Cordia.lasiocalyx is the species I chose as the single predictor variable. When I try to update the model with an exponential error structure using this code:

`standleyi_1var_exp = update(standleyi_1var_lm, corr=corExp((form=~x + y)))`

It gives this error message:
Error in Initialize.corSpatial(X[[i]], ...) : 'range' must be > 0 in "corSpatial" initial value

Just wondering what I'm doing wrong and if I'm missing something. Thanks!

**Comment by dmcglinn** [comment]
Hey @strangebb thanks so much for your question! I should have anticipated this as it was an issue that students previously noted in #22 and #23. Essentially the easiest solution is to just define x and y as the first and second columns of `BCI_xy` and then your code should work. 
```r
x <- BCI_xy$x
y <- BCI_xy$y
standleyi_1var_exp <- update(standleyi_1var_lm, corr=corExp(form = ~ x + y))
```
To be honest I'm not sure why this does not work: `tandleyi_1var_exp <- update(standleyi_1var_lm, corr=corExp(form = ~ BCI_xy$x + BCI_xy$y))` but it does not. 

Note also I think you may have had one extra set of parentheses that you did not need.

**Comment by strangebb** [comment]
Awesome thank you so much!
