### ISSUE TITLE
install failing and some graphing help

### ISSUE THREAD

**Issue by patelac** [dmcglinn/quant_methods#48]
I'm trying to install ggplot2 so I can use it for some scatterplots, but I keep getting this error:

Error in library.dynam(lib, package, package.lib) : 
  shared object ‘stringi.so’ not found

And 'stringi.so' will not install at all.

Also a simple question, can someone advise me on how to increase the increments on an axis in a normal plot? I understand increasing the max and min, but I am trying to spread out the increments on the x-axis so it's not as cluttered.

Thanks,

**Comment by dmcglinn** [comment]
Hey @patelac I'm sorry you're having trouble getting things installed. I looked into this and found this thread: 

https://support.rstudio.com/hc/en-us/community/posts/204866908-stringi-so-not-found

I logged into uniola under your account and I tried to install the `stringi` package which is what is recommended (above). R gave an error that told me that there was a lock file on that package. This usually occurs for example when you interrupt a package that is halfway through installation. After I deleted the lock file and the partially installed `stringi` package I was able to install a fresh copy of it without errors then I was able to install the `ggplot2` package. 

With regards to your second question the only way to spread out values is to zoom in on the range of the axis you consider. so you could only consider the first quartile of the data along the x-axis for example. Alternatively sometimes transformations of the data can be very helpful in spreading or compressing portions of a variable. So for example a log transformation is useful for spreading out small values while compressing large values. Some times this is useful for example when working with variables that have a roughly log-normal distribution (e.g.,most distributions of wealth).
