### ISSUE TITLE
Euclidean distance between two matrices of unequal dimensions

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#49]
Hey I need to create a distance matrix between two matrices of unequal dimensions and it appears I can't use the dist() function so I was wondering how I might go about doing that. One matrix is an xy matrix with geographic coordinates for a list of 50 or so sample sites and the other is an xy matrix with coordinates for 6 specific points on a map.

Thanks in advance!

-James

**Comment by dmcglinn** [comment]
Here's a snippet of R code that should give you a push in the right direction. Essentially you're just going to put those reference points into your matrix of sample coordinates. Then you'll take advantage of the fact that dist computes every possible pairwise distance. You're only going to be interested in certain distances from the resulting distance matrix so you'll just need to subset those out. 

```r
ref_pt = c(1, 1)
coords = expand.grid(1:3, 1:3)
distances = as.matrix(dist(rbind(ref_pt, coords)))[-1,1]

plot(coords, type = 'n')
points(ref_pt[1], ref_pt[2], col='red', pch = 19)
text(coords, labels = 1:9)
plot(distances)
```

**Comment by strangebb** [comment]
Awesome, thank you so much!
