### ISSUE TITLE
`git clone` to specific location instead of root

### ISSUE THREAD

**Issue by frie-knuth** [dmcglinn/quant_methods#5]
When I use `git clone` to clone my existing repository to my mac it by default places the folder it at the user root. How can I specify a different location to place to cloned folder into?

**Comment by dmcglinn** [comment]
You should be able to simply navigate in the terminal to what ever directory you would like to clone into, so for example
```
# change directory to home
cd ~
# check the path of your directory
pwd
# Now let's suppose I want to clone a repo into the sub-directory my_repos
# I could cd into my_repos 
cd my_repos
git clone git@github.com:some_remote_repo
# the above will create a folder called some_remote_repo in the my_repos directory
```

**Comment by frie-knuth** [comment]
got it - forgot that one has to change the working directory prior to running the commands.

btw I found out you can just drag and drop a file or folder into terminal on the mac and it will populate the file path. pretty sweet.

I added you as a collaborator to my newly private repository. Let me know if that shows up for you. 

Thanks again!!
