### ISSUE TITLE
Distance unit of measurement

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#50]
I computed a distance matrix between a set of 50 sample sites (decimal latitude and longitude) and a set of 6 specific geographic coordinates (also decimal lat/long). For properly labelling graphs that use this dist() output, how do I go about finding the specific unit of distance measurement that dist() function put out, given the coordinates were in decimal format?

Thanks, 
James

**Comment by klhill1990** [comment]
I've ran into similar problems in GIS before. I'm not sure how this would work in R, but in GIS there's a difference between 'geographic' and 'projected' coordinate systems.  Geographic coordinate systems (decimal degrees) represent the actual 3D globe, whereas projected coordinate systems (like UTMs) are distorted onto a 2D plane. To measure distances or areas in meters or miles, you may need to convert the underlying coordinate system to a projected system. This is just what I've learned from GIS, so I'm not sure whatever R package you are using handles this distinction.

**Comment by dmcglinn** [comment]
I was going to mention this to you. You actually need to compute arc distances not Euclidean distances because lat long are spherical coordinates. The easier alternative is to transform your coordinates to a UTM projection where you can use Euclidean distances. Units are meters in UTM. You will have to define the appropriate zone for your study site.

Dan

**Comment by strangebb** [comment]
Ok thanks, how could you convert coordinates to UTM? Is there a particular function?

**Comment by dmcglinn** [comment]
We did projections in the GIS lesson 

Dan

**Comment by strangebb** [comment]
Ok thanks. Do I need to transform decimal to UTM coordinates for all spatial analyses, or just for my analyses of abundance in relation to distance to nearest tidal creek?

**Comment by dmcglinn** [comment]
I would just do it for all. It most likely won’t change inference but the units of distance will be correct.

Dan

**Comment by strangebb** [comment]
Ok thanks sounds good
