### ISSUE TITLE
Function for subsetting a matrix by columns

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#52]
Hey I'm trying to write a function that will go through a community matrix and create subsets for each column (i.e. species). Here's what I have so far:

```
shark.subset = function(e) {
  subset_titles = c("blacktip1", "sandbar1", "finetooth1", "sharpnose1", "bonnethead1", "hammerhead1")
      for (k in 1:ncol(e)) {
          for (u in seq_along(subset_titles)) {
          subset_titles[u] = e[ , k]
          }
      } 
} 
```

Where e = the matrix I'm trying to subset
subset_titles = the titles of the subsets I want 

But I get this error message:
"number of items to replace is not a multiple of replacement length"

Any help would be appreciated. Thanks!

-James

**Comment by strangebb** [comment]
Essentially, this is what I'm trying to avoid by writing a function:

```
blacktip1 = sharkcomm[ , "Blacktip"]
sandbar1 = sharkcomm[ , "Sandbar"]
finetooth1 = sharkcomm[ , "Finetooth"]
sharpnose1 = sharkcomm[ , "Sharpnose"]
bonnethead1 = sharkcomm[ , "Bonnethead"]
hammerhead1 = sharkcomm[ , "Hammerhead"]
```

**Comment by dmcglinn** [comment]
Hey @strangebb good news there's no need for a function in this case because the function `subset` takes care of this with the argument `select`. 

Give this a try
```r
# to only keep Blacktip 
subset(sharkcomm, select = Blacktip)
# to keep all columns except Blacktip
subset(sharkcomm, select = -Blacktip)
```

**Comment by dmcglinn** [comment]
Oh and in reference to the error you were getting that is because you first defined the variable `subset_titles` as a vector of names then you tried to assign each element of it a vector in the for loop but each element of a vector can only hold one vector element which cannot in this case be an entire vector. The data class `list` is much more forgiving and flexible though.

**Comment by strangebb** [comment]
Awesome, thank you so much!
