### ISSUE TITLE
loading a .csv from a private github repo

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#53]
For my project I have to load in data from a private GitHub repo. I've been using the data's URL, but I realized that this URL seems to change every 7-10 days and I was wondering if there's an easier way to access the data from within R studio even though my repository is private

**Comment by dmcglinn** [comment]
Why don't you just clone the private repo to your local hard drive and then the data file will be local. It is not suggested to use a url for importing a dataset if it keeps changing.
