### ISSUE TITLE
Using Vegan and doing NMDS "species" labels

### ISSUE THREAD

**Issue by enriqueza** [dmcglinn/quant_methods#54]
Hello all,

I know it's a little late, but I was wondering if anyone knew if you could change the labels when it comes to plotting an NMDS. I'm using vegan and was just wondering if that was part of the package? I separated my dataframe by class, not species, but arguments acceptable are "sites" and "species". Here is my code to plot:

```r
plot(classNMDS)
orditorp(classNMDS,display = "species",cex=0.5,air=0.05)
```
I don't know if this question makes sense. Thanks anyway!

**Comment by dmcglinn** [comment]
the function `orditorp` has an argument called `labels` that should do the trick
