### ISSUE TITLE
graphs wont appear anymore

### ISSUE THREAD

**Issue by patelac** [dmcglinn/quant_methods#55]
So I am having trouble with Uniola. The function ggplot was working yesterday but it isn't today. I am just trying to get screenshots of my graphs and add some last minute edits to them. I keep receiving three different warning or errors:

1. This function is not available for version 3.5.2
2. Could not find function
3. There is no package called ggplot

Any help or suggestions?

**Comment by dmcglinn** [comment]
The package is not called `ggplot` it is called `ggplot2`
