### ISSUE TITLE
Loading Data Help

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#56]
Hey I'm trying to change where my project loads data from. Instead of using a URL, I'm trying to make the code load in data from the /Data file in my project directory file when it is cloned from GitHub to the desktop.

Here is the code I'm using:

`Bulls16_18 = read.csv(file = "./shark-dist-bullsbay/Data/BullsBay16-18.csv", header = TRUE)`

But I keep getting this error message:

Error in file(file, "rt") : cannot open the connection

Any help would be much appreciated. Thanks!

**Comment by juliapiscioniere** [comment]
For my data, I just made the path from inside the directory, so, for yours it would be: “/Data/BullsBay16-18.csv” 

Hope this helps! If it doesn’t, typing the error message into google with the programming laungauge can help sometimes.

**Comment by czwartackisr** [comment]
Hey James,
You shouldn't need "file =" when reading a csv, I don't think.  Also, if your working directory is "shark-dist-bullsbay", then you just need to type:
`read.csv("./Data/BullsBay16-18.csv", header = TRUE)`

**Comment by strangebb** [comment]
Awesome thanks! For some reason it didn't work with one period before the /Data but it worked with two:

`Bulls16_18 = read.csv("../Data/BullsBay16-18.csv", header = TRUE)`
