### ISSUE TITLE
Basics Homework Plotting Issue

### ISSUE THREAD

**Issue by mosscr** [dmcglinn/quant_methods#57]
Hey!

I cannot figure out how to plot the relationship between scale and richness. It keeps giving me errors when I use the plot function listed in the lesson and it also gives me errors when I try to even read the data file. I'm not entirely sure what is going on or how to fix it. 

Thank you!

**Comment by dmcglinn** [comment]
Hey @mosscr thank you for submitting the first post of the semester! Nice job! Can you please provide us a little more information include your R code and the associated error from R? Thanks!

**Comment by mosscr** [comment]
Here is a screenshot of the problems.

<img width="960" alt="2020-01-15 (1)" src="https://user-images.githubusercontent.com/59877798/72488725-d0e31880-37df-11ea-9755-0f21207ab165.png">

**Comment by dmcglinn** [comment]
Hey @mosscr thanks for that! To make it easier for us to address your question simply copy and paste the offending R code and errors. But based on that screen shot I can see that the function `plot` is being supplied information that it was not expecting. If you look at the documentation of `plot` using `?plot` you'll see that it expects `x` and a `y` values. These should be vectors and in your specific case they should be the vectors from `tgpp` called `scale` and `richness`. With that in mind see if you can take another crack at getting `plot` to work for you. Don't hesitate to write back if you're still having trouble.

**Comment by mosscr** [comment]
Thank you!

I've gotten the problem with being able to read the data fixed, but it's giving me the error: "Error in plot.function(scale, richness) : object 'richness' not found" whenever I try to plug richness in for the Y variable. I've been attempting it using the ?plot, but I'm not sure what information from the list it provides needs to be included in the code.

**Comment by jgcaughro** [comment]
Hey @mosscr, richness and scale are columns inside the data frame tgpp. You can access columns from a data frame using a $ like this -> dataframe_name$column_name

Hope this helps! 
J

**Comment by mosscr** [comment]
I've gotten the plot! Thank you so much!
