### ISSUE TITLE
#6 on the Intermediate Assignment

### ISSUE THREAD

**Issue by CassandraEvanchuk** [dmcglinn/quant_methods#59]
I can't seem to get the code output NA.

```
y=NULL
x<- c(1,2,3,4,5,6,7,8,9,10)
for (i in x) 
  y[i] = sum(x[1:i]) 
    if (y[i]<=10) {
    print(y)
  } else if (y[i]>10) {
    print ('NA')
  }
 
y
```

**Comment by dmcglinn** [comment]
Hey @CassandraEvanchuk so you just have a simple bracket mistake in your for loop. If you don't include the curly brackets the R loop will not return any errors but it will only run the first full line of code after the for loop - confusing I know. Try this out: 

```r
y <- NULL
x <- 1:10
for (i in x) {
  y[i] = sum(x[1:i]) 
  if (y[i]<=10) {
    print(y)
  } else if (y[i]>10) {
    print ('NA')
  }
} 
y
```

**Comment by CassandraEvanchuk** [comment]
@dmcglinn 

I tried that, but it is returning this! 
![Screen Shot 2020-01-20 at 9 13 04 PM](https://user-images.githubusercontent.com/59878914/72769742-baff9a00-3bc9-11ea-894e-1b02e468cade.png)

**Comment by dmcglinn** [comment]
If you want `y` to capture the `NA` values you just need to change those print statements to assignment  statements `y[i] <- NA`

**Comment by CassandraEvanchuk** [comment]
@dmcglinn Got it!! Thank you so much!!
