### ISSUE TITLE
Univariate Modelling HW Issue 

### ISSUE THREAD

**Issue by mosscr** [dmcglinn/quant_methods#60]
I'm having issues figuring out how to create models for the specific species instead of just for the whole data set. Could anyone help with this?

Thanks!

**Comment by reisenfeldk** [comment]
Hi!  You have to create a subset of the data.  There are a few ways to do this but I use the following: 

abiefra <- trees[trees$spcode=="ABIEFRA",]

You could also use species name instead of code. I hope this helps!

**Comment by nickstrait** [comment]
The way I did it was:

lm(formula = cover ~ plotsize.... data = trees, subset = species == "Acer rubrum")

**Comment by mosscr** [comment]
Thank you for the responses!

I was able to create the abiefra subset, but I'm not entirely sure how to make a plot out of that.

**Comment by mosscr** [comment]
Update: I figured it out!
