### ISSUE TITLE
Spatial Modeling Assignment

### ISSUE THREAD

**Issue by millertp1** [dmcglinn/quant_methods#63]
Confused on #2 building a model that only looks at one variable, has anyone successfully generated a linear model using the codes from the lesson?

**Comment by dmcglinn** [comment]
can you please provide some code for what you have tried so that we can better understand where you are having trouble.

**Comment by mosscr** [comment]
I am also having this issue. It gives me the error: "invalid type (list) for variable" no matter what variable I try.

**Comment by dmcglinn** [comment]
Can you please post your code snippet

Dan

**Comment by NicoleStrauss** [comment]
I think I had the same issue here, but I'm on my phone and can't access R at the moment. I'll try to explain -
Make sure that the first two variables are the response and the predictor. So (Drypetes.standleyi ~ other.tree, data = data.frame). It didnt work for me until I just used the column names alone, kept getting the same "list" error.

**Comment by mosscr** [comment]
@NicoleStrauss That seems to have worked for me! Thank you!

**Comment by jtgood** [comment]
2 questions: 
1) Does anyone have a code to use a spherical model for the second question?
2) How can I fix my ANOVA to have a 'form' with a two sided formula when comparing the statistics of my models?

**Comment by dmcglinn** [comment]
Hey @jtgood 
1. can you share what you've tried for the spherical model so that we can help you trouble shoot it?
2. I think by ANOVA you mean the coefficient summary table that is output by the function `summary`. If you want to use the form argument remember you have use the function `nlme::gls`.

**Comment by jtgood** [comment]
Hi @dmcglinn,
Thank you for the suggestions for summary and nlme::gls!
As for the spherical model, I don't know how to begin a function modeled after the given equation in the spatial modeling lesson.  I have been using exponential and quadratic equations, but I can always see you before/after class.

Thanks!

**Comment by dmcglinn** [comment]
Hey @jtgood ahh I understand now! I didn't demonstrate `corSpher` in the lesson - I'll have to add that.  Check out the documentation of `nlme::corClasses`: 

https://www.rdocumentation.org/packages/nlme/versions/3.1-144/topics/corClasses

This lists every builtin model for correlation structure. No need to build your own in this case although they do have helper functions if that is something you decide to pursue.
