### ISSUE TITLE
where is MASS (4th ed) by Venables and Ripley?

### ISSUE THREAD

**Issue by Lexie-DelViscio** [dmcglinn/quant_methods#68]
I can't find MASS (4th ed) by Venables and Ripley in the dropbox for books to download? Is this one somewhere else?

**Comment by dmcglinn** [comment]
Hey sorry about that here is a link if you didn't get that sorted out: 
https://www.researchgate.net/profile/Bill-Venables/publication/224817420_Modern_Applied_Statistics_With_S/links/5f5481f092851c250b96c0a9/Modern-Applied-Statistics-With-S.pdf

Thanks to @sydowpw for finding this link
