### ISSUE TITLE
Car installation

### ISSUE THREAD

**Issue by emilydombrowski** [dmcglinn/quant_methods#69]
```r
install.packages("car")
library(car)
```
I haven't been able to install the car package on my computer. I've tried to install with receive the following messages: 

```
Warning in install.packages :
  installation of package ‘car’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/00/y8gd96qn04qg98qzdvj9k5yh0000gn/T/RtmpDZOdih/downloaded_packages’
```

When I type `library(car)` it also produces an error message...I've tried with and without quotations, etc. 

Is anyone else having this issue? Thank you in advance!

**Comment by dmcglinn** [comment]
Hey @emilydombrowski this kind of error usually occurs when one of the packages that `car` depends on has trouble installing. In this case that may be `lme4`. Can you please just try: 

```r
install.packages('lme4')
```
See if that gives and errors. Thanks!

**Comment by emilydombrowski** [comment]
It ended up being a problem with how I was responding to a prompt in the console that appeared when downloading the package (I needed to respond 'no' instead of 'yes'). I successfully downloaded the package and have been using the associated ANOVA function. Thank you!
