### ISSUE TITLE
installed and loaded vegan but no cleanplot.pca

### ISSUE THREAD

**Issue by Lexie-DelViscio** [dmcglinn/quant_methods#72]
Hi! Im working through the lesson now and I installed and loaded the vegan library just fine, and I was able to compute tree_pca and plot it normally with plot and biplot just fine. But, when I try to run cleanplot.pca(tree_pca) there is an error message that the function "cleanplot.pca" could not be found. Is there somewhere else I need to install/ load this from, or have the versions changed changing the function name maybe? Is anyone else having this issue?

**Comment by dmcglinn** [comment]
Hey Lexie you need to load the functions store here using the function source

https://github.com/dmcglinn/quant_methods/blob/gh-pages/scripts/utility_functions.R

Dan

**Comment by Lexie-DelViscio** [comment]
thanks!!
