### ISSUE TITLE
Error in getCovariate.corSpatial(object, data = data) :    cannot have zero distances in "corSpatial"

### ISSUE THREAD

**Issue by jacksonbarrattheitmann** [dmcglinn/quant_methods#74]
```r
pred_sp <- BCI[ , sp_ids]
print(pred_sp)

# need to rename columns then specify in the model
# using pred_sp$a ... 
names(pred_sp) <- c('Cord', 'Hirt', 'Picra', 'Quass',
                    'Taber', 'Tratt', 'Xylo', 'Dryp')
# Model 1 - using just one species
sp_lm <- gls(Dryp ~ Hirt, data = pred_sp)

sp_exp <- update(sp_lm, corr = corExp(form = ~Dryp + Hirt, nugget = T))

# after running this last line of code I get this error:
Error in getCovariate.corSpatial(object, data = data) : 
  cannot have zero distances in "corSpatial"
```

**Comment by dmcglinn** [comment]
Thanks @jacksonbarrattheitmann for submitting this issue. Quick note I edited your comment for formatting following the guidelines posted [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). 

So the main point of confusion seems to be that you use the function `corExp` to model the lack of dependence of the samples using their spatial positions but you have supplied that function both the response variable and the independent variable. I can see why you might have gotten this confused now based upon the lesson where we used the syntax `..., cor = corExp(form = ~ x + y)`. In the spatial lesson the variables `x` and `y` were not symbolic for the dependent and independent variables but rather for the x- and y-coordinate of the samples. Specifically the column names of the coordinates where `x` and `y`. So you'll want to see were the BCI coordinates are stored and named and then reference them in the function. Let me know if you need any more nudges in the right direction.

**Comment by jacksonbarrattheitmann** [comment]
thanks @dmcglinn . I realized this once I went back into the R book and realized all the examples were actually using the spatial coordinate variables to model the dependence. I then realized *x* and *y* were the spatial coordinates. Thanks.
