### ISSUE TITLE
Univariate: r^2

### ISSUE THREAD

**Issue by houstonhannah** [dmcglinn/quant_methods#75]
Hi, 

I am having trouble understanding the r^2 values for the LM models (question 1). I got that for Abies, 24% of the variability observed in the target variable (cover) was explained (adjusted r^2 = 0.2406) while in Acer 17% of the variability observed in the target variable was explained by the model (adjusted r^2 = 0.1726), but why might this be the case? I expected that Aibes would have less of the observed variability explained due to the amount of "0" cover points. 

```
#modeling for acer, looking at all variables 
acer_mod_lm <- lm(cover ~ ., data=acer)
Anova(update(acer_mod_lm, . ~ . -1), type=3) #update drops intercept because we have a categorical variable
summary(acer_mod_lm)
#Anova and Summary generate same p-value

#modeling for abies, looking at all variables 
abies_mod_lm <- lm(cover~ ., data=abies)
Anova(update(abies_mod_lm, . ~ . -1), type=3) #update drops intercept because we have a categorical variable
summary(abies_mod_lm)
#Anova and Summary also generate same p-value

```
Thanks for your help! 

-Hannah

**Comment by dmcglinn** [comment]
@houstonhannah thank you so much for our first issue of the semester!! Great questions here. One explanation for why the generalists may have a lower explained variance is that it simply occurs everywhere. In fact Red Maple is a very ubiquitous tree in many habitats of the Eastern Deciduous forest from low to mid-elevations. Side note: this is one of the reasons the Asian longhorn beetle invasion is very troubling.  

One thing I noticed in your code is that in class I was rushing through how to interpret categorical variables and I misspoke by saying you should drop the intercept term when carrying out a type 3 Anova. That was incorrect. You should not do that. You can simply just use `Anova(acer_mod_lm, type =3)`. It is true that the line of output from that type 3 anova includes the intercept which is not informative in this context, but the F-statistics and p-value for your specific categorical variable of interest will be correct in this case.
