### ISSUE TITLE
Error trying to push onto Github

### ISSUE THREAD

**Issue by kelseymartin1** [dmcglinn/quant_methods#76]
I'm encountering an error when trying to push my assignment onto Github. The error states:

To github.com:kelseymartin1/Assignments.git
 ! [rejected]        HEAD -> main (non-fast-forward)
error: failed to push some refs to 'github.com:kelseymartin1/Assignments.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I tried pulling then pushing again, but it did not work.

Any suggestions?

**Comment by dmcglinn** [comment]
I suggest looking at the commit log here: 
https://github.com/kelseymartin1/Assignments/commits/main

And compare it with the commit log you have on your local machine on the git tab. The only reason this will occur is if you have commits on github that you do not have locally.

**Comment by dmcglinn** [comment]
Hey @kelseymartin1 are you good now. Did my solution of cloning a fresh version of your repo and then copying and pasting in your changes work?
