### ISSUE TITLE
Error when trying to compile code

### ISSUE THREAD

**Issue by mandim17** [dmcglinn/quant_methods#77]
Hi! Every time I try to compile my code I get this error: Error in contrib.url(repos, "source") : trying to use CRAN without setting a mirror. I can't figure out how to fix it.

**Comment by dmcglinn** [comment]
I can see from your code:

https://github.com/mandim17/r_class_hw/blob/main/tree%20hw%20m.R#L12-L19

That you are trying to install packages while compiling the report. This is not recommended and in general you should only install a package once unless a new version has been released or something like that. Remove all those install commands from your code.

**Comment by mandim17** [comment]
Thank you! I removed the install commands, but now I am getting this error: Error in metaMDS(comm) : could not find function "metaMDS"
Calls: <Anonymous> ... withVisible -> eval_with_user_handlers -> eval -> eval
Execution halted

**Comment by dmcglinn** [comment]
you still need the line of code that loads the vegan library that is
where the function metaMDS is stored use

library(vegan)

We typically load all the necessary libraries at the top of the script.

On Wed, Feb 22, 2023 at 9:20 PM mandim17 ***@***.***> wrote:
>
> Thank you! I removed the install commands, but now I am getting this error: Error in metaMDS(comm) : could not find function "metaMDS"
> Calls: ... withVisible -> eval_with_user_handlers -> eval -> eval
> Execution halted
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
Daniel J. McGlinn, PhD
Associate Professor
https://www.mcglinnlab.org
mailing address:
Department of Biology
College of Charleston
66 George Street
Charleston, SC 29424
physical address:
Rita Hollings Science Center (office: 239, lab: 292)
58 Coming Street, Suite 245-255
Charleston, SC 29401

**Comment by dmcglinn** [comment]
is this resolved yet?
