### ISSUE TITLE
Spatial HW: Q 2

### ISSUE THREAD

**Issue by houstonhannah** [dmcglinn/quant_methods#78]
Hello! 

I am having trouble formatting the gls for question 2 when including the list of species you provided as the predictor variables. I am met with the error: Error in model.frame.default(formula = dry_sta ~ bci_sub, drop.unused.levels = TRUE) :
invalid type (list) for variable 'bci_sub'.  Any suggestions would be appreciated! Thanks!

`#Making Model 2: include all species as predictor variables

dry_sta <- BCI$Drypetes.standleyi

bci_sub <- subset(BCI, select =  c("Cordia.lasiocalyx", "Hirtella.triandra",
           "Picramnia.latifolia", "Quassia.amara",
           "Tabernaemontana.arborea", "Trattinnickia.aspera", 
           "Xylopia.macrantha"))

bci_sub_spat <- cbind(bci_sub, BCI_xy) #adds spatial location data
           
gls_prespec <- lm(dry_sta ~ bci_sub)
gls_prespec

summary(gls_prespec)`

**Comment by houstonhannah** [comment]
Issue update: Unlisting bcd_sub helped, but now I have a different error:  Error in model.frame.default(formula = dry_sta ~ bci_sub, drop.unused.levels = TRUE: 
invalid type (list) for variable 'bcc_sub'

`dry_sta <- BCI$Drypetes.standleyi

bci_sub <- subset(BCI, select =  c("Cordia.lasiocalyx", "Hirtella.triandra",
           "Picramnia.latifolia", "Quassia.amara",
           "Tabernaemontana.arborea", "Trattinnickia.aspera", 
           "Xylopia.macrantha"))
bci_sub <- unlist(bci_sub)

bci_sub_spat <- cbind(bci_sub, BCI_xy) #adds spatial location data
           
gls_prespec <- lm(dry_sta ~ bci_sub)
gls_prespec

summary(gls_prespec)`

**Comment by dmcglinn** [comment]
Hey @houstonhannah you're very close but two things to note: 
1) don't unlist the data.frame - not really helpful here
2) you just forgot to provide `dat_sub` as the data argument to the function gls. Try: 

`gls(dry_sta ~ . , data = dat_sub)` 

If you want to include all the other species as predictors. 

Quick note about formatting in markdown if you want to do an inline piece of code then just wrap the code in the single tick mark. If you have a code chunk like you have above then wrap it in three ticks.  Use the "Preview" window to make sure it looks correct. 

Dan

**Comment by houstonhannah** [comment]
Thank you Dan! 

Follow up question: How does that change translate to Variogram coding? I have used both bci_sub and bci_sub_spat and was met with errors. 
```
bci_sub <- subset(BCI, select =  c("Cordia.lasiocalyx", "Hirtella.triandra",
           "Picramnia.latifolia", "Quassia.amara",
           "Tabernaemontana.arborea", "Trattinnickia.aspera", 
           "Xylopia.macrantha"))

bci_sub_spat <- cbind(bci_sub, BCI_xy) #adds spatial location data

#use function Variogram for all predictor species 
vario_prespec <- Variogram(gls_prespec, form= ~ BCI$Drypetes.standleyi + bci_sub_spat, resType = 'response')

#compare to a plot we make on our own 
res <- residuals(gls_prespec)
res_var <- dist(res)^2 * 0.5
plot(dist(BCI[, c(BCI$Drypetes.standleyi, bci_sub_spat)]), res_var)
lines(lowess(dist(BCI[, c(BCI$Drypetes.standleyi, bci_sub_spat)]), res_var), col='red', lwd=2)
abline(v = max_dist, col='red', lwd=3, lty=2)
```

**Comment by dmcglinn** [comment]
The key here is that the argument `form` to the function `Variogram` has to specify the names of the spatial coordinates in this case `x` and `y`.
