### ISSUE TITLE
Spatial Modeling HW - Plotting BCI_xy against individual abundances

### ISSUE THREAD

**Issue by Weberlm** [dmcglinn/quant_methods#85]
This may be a bit of a silly question, but I know that in order to properly analyze the spatial dependences of my selected common and rare species, I need to plot BCI_xy against their individual abundance, sort of like this:

`plot(BCI_xy,abu)`

(except that abu should be an individual's abundance)

where abu is `colSums(BCI)`

However I'm blanking a bit on a way that I can take only an individual species' abundance so that I can plot it. Does anyone have any suggestions?

**Comment by dmcglinn** [comment]
Hey @Weberlm thanks for the question. So if you want to define `abu` as a single column of BCI then you simply need to take the column (i.e., species) you are interested in like so: 

```
# let's say I want to examine the 3rd species
abu <- BCI[ , 3]
# now I have two ways to look for spatial dependance,
# option 1: make a map
plot(BCI_xy, cex = abu / max(abu))
# option 2: plot geographic distance by distance in abundance
geo_dist <- dist(BCI_xy)
abu_dist <- dist(abu)
plot(geo_dist, abu_dist)
```
hope that helps.

**Comment by dmcglinn** [comment]
checking in on this...

**Comment by Weberlm** [comment]
This helped a lot, thank you!
